### PR TITLE
Update the TransportMode type reference

### PR DESCRIPTION
**Pull request by sebouh00**

### CODE REVIEW

**Comment by sebouh00** [comment]
I see the RN method accepts string as transport mode type, then resolves it with valueOf(). Is there a list of acceptable strings defined somewhere?

**Comment by jiricrispeyn** [comment]
Hi Sebouh,

I was checking our README.md and noticed that we give following documentation regarding TransportMode

screenshot 2019-03-01 at 10 35 31

Though, in our RN method bridge for `startTrip`, we expect a String value indeed.

It might be best to align our bridge implementation with the native implementation.
Could you give clarification how this is handled?

kr

Jiri

**Comment by sebouh00** [comment]
The RN method seems to call valueOf on the Android enum, which will only work if the input string exactly matches the enum identifier.

I think it's best to accept an enum in js that maps to a proper Android and iOS enum. For Android, it should map to `com.sentiance.sdk.trip.TransportMode`. For iOS, it should map to `SENTTransportMode` (which is what you have in the readme).

**Comment by jiricrispeyn** [comment]
#47

**Pull request closed without merging**
